### ISSUE TITLE
Stop pushing bundled JavaScript in lib/

### ISSUE THREAD

**Issue by retrixe** [RSG-Group/RSG-Chess-API#5]

**Comment by radi-cho** [comment]
Yeah, already "planned". Currently I'm pushing bundles because often I'm testing some stuff on my phone. There I can use git and node but the file system don't allow me to run webpack...

**Comment by retrixe** [comment]
Why? What application do you use

**Comment by radi-cho** [comment]
Termux

**Comment by retrixe** [comment]
Termux has issues with Webpack?

**Comment by radi-cho** [comment]
not with webpack, but with things that change and creates files - permission denied and EPERM errors. There was some confirmed GitHub issues, but I didn't used Termux for a while.

**Comment by retrixe** [comment]
Use `chmod` and `chown` Linux utilities in that case.
